### ISSUE TITLE
Cannot crawl papers from openreview

### ISSUE THREAD

**Issue by DongXingshuai** [EdisonLeeeee/-ICLR2023-OpenReviewData#1]
Hi there, I tried to run the parse_data.py to crawl data from openreview. Unfortunately, it did not work. The following are the error messages. Is anybody can give me a hand? Thank you!

python crawl_paperlist.py
Traceback (most recent call last):
  File "crawl_paperlist.py", line 24, in <module>
    WebDriverWait(driver, 30).until(cond)
  File "D:\LenovoSoftstore\Install\Anaconda3\envs\nlp\lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
        GetHandleVerifier [0x00007FF7F77B3DB2+61490]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7F7746002+740642]
        (No symbol) [0x00007FF7F751B8AE]
        (No symbol) [0x00007FF7F75632F4]
        (No symbol) [0x00007FF7F7563405]
        (No symbol) [0x00007FF7F759FCE7]
        (No symbol) [0x00007FF7F758394F]
        (No symbol) [0x00007FF7F7557021]
        (No symbol) [0x00007FF7F759CE21]
        (No symbol) [0x00007FF7F75836E3]
        (No symbol) [0x00007FF7F7555EAA]
        (No symbol) [0x00007FF7F755518B]
        (No symbol) [0x00007FF7F7556634]
        Microsoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00007FF7F7978D69+1207369]
        (No symbol) [0x00007FF7F75D5304]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7F76990F1+32273]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7F76919E9+1801]
        Microsoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00007FF7F7977944+1202212]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7F774E998+19784]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7F774AE54+4612]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7F774AF86+4918]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7F773F451+713073]
        BaseThreadInitThunk [0x00007FFFE8517614+20]
        RtlUserThreadStart [0x00007FFFE8BC26B1+33]

**Comment by marcuswang6** [comment]
Me too.
